spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true
    properties:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: "dev"

server:
  error:
    include-message: always